apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: support